import mongoose, { Schema, Document, Types } from 'mongoose';

// ──────────────────────────────────────────
// Quiz Question (embedded subdocument)
// ──────────────────────────────────────────

/**
 * A single multiple-choice option.
 */
export interface IOption {
  label: string;       // "A", "B", "C", "D"
  text: string;        // The option text
}

/**
 * A single multiple-choice question.
 */
export interface IQuestion {
  _id: Types.ObjectId; // auto-generated by Mongoose
  questionText: string;
  options: IOption[];
  correctLabel: string; // matches one of the option labels
  sortOrder: number;
}

/**
 * Convert-safe question view — strips correctLabel.
 */
export interface QuestionPublicView {
  id: string;
  questionText: string;
  options: IOption[];
  sortOrder: number;
}

/**
 * Admin question view — includes correct answer.
 */
export interface QuestionAdminView {
  id: string;
  questionText: string;
  options: IOption[];
  correctLabel: string;
  sortOrder: number;
}

// ──────────────────────────────────────────
// Quiz Document
// ──────────────────────────────────────────

/**
 * Quiz document interface.
 * One quiz per lesson (enforced by unique index).
 */
export interface IQuiz extends Document {
  _id: Types.ObjectId;
  lessonId: Types.ObjectId;
  courseId: Types.ObjectId;
  title: string;
  description: string;
  questions: IQuestion[];
  passingScore: number;   // percentage (default 70)
  maxAttempts: number;     // 0 = unlimited
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Convert-safe quiz view — no correct answers exposed.
 */
export interface QuizPublicView {
  id: string;
  lessonId: string;
  title: string;
  description: string;
  questions: QuestionPublicView[];
  passingScore: number;
  maxAttempts: number;
  totalQuestions: number;
}

/**
 * Full admin quiz view.
 */
export interface QuizAdminView {
  id: string;
  lessonId: string;
  courseId: string;
  title: string;
  description: string;
  questions: QuestionAdminView[];
  passingScore: number;
  maxAttempts: number;
  totalQuestions: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// ── Option schema (embedded) ──
const optionSchema = new Schema<IOption>(
  {
    label: {
      type: String,
      required: true,
      trim: true,
      maxlength: 5,
    },
    text: {
      type: String,
      required: true,
      trim: true,
      maxlength: 1000,
    },
  },
  { _id: false }
);

// ── Question schema (embedded) ──
const questionSchema = new Schema<IQuestion>({
  questionText: {
    type: String,
    required: true,
    trim: true,
    maxlength: 2000,
  },
  options: {
    type: [optionSchema],
    validate: {
      validator: (v: IOption[]) => v.length >= 2 && v.length <= 6,
      message: 'Each question must have 2-6 options',
    },
  },
  correctLabel: {
    type: String,
    required: true,
    trim: true,
  },
  sortOrder: {
    type: Number,
    required: true,
    min: 1,
  },
});

// ── Quiz schema ──
const quizSchema = new Schema<IQuiz>(
  {
    lessonId: {
      type: Schema.Types.ObjectId,
      ref: 'Lesson',
      required: true,
    },
    courseId: {
      type: Schema.Types.ObjectId,
      ref: 'Course',
      required: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 300,
    },
    description: {
      type: String,
      trim: true,
      default: '',
      maxlength: 2000,
    },
    questions: {
      type: [questionSchema],
      validate: {
        validator: (v: IQuestion[]) => v.length >= 1 && v.length <= 50,
        message: 'Quiz must have 1-50 questions',
      },
    },
    passingScore: {
      type: Number,
      default: 70,
      min: 1,
      max: 100,
    },
    maxAttempts: {
      type: Number,
      default: 0, // 0 = unlimited
      min: 0,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
    toJSON: {
      transform(_doc, ret: Record<string, unknown>) {
        delete ret.__v;
        return ret;
      },
    },
  }
);

// One quiz per lesson (enforced)
quizSchema.index({ lessonId: 1 }, { unique: true });

// Lookup by course
quizSchema.index({ courseId: 1 });

// ──────────────────────────────────────────
// Quiz Attempt Document
// ──────────────────────────────────────────

/**
 * A single answer submitted by a convert.
 */
export interface ISubmittedAnswer {
  questionId: string;
  selectedLabel: string;
  isCorrect?: boolean;  // populated after grading
}

/**
 * Quiz attempt document — immutable record of each submission.
 */
export interface IQuizAttempt extends Document {
  _id: Types.ObjectId;
  quizId: Types.ObjectId;
  lessonId: Types.ObjectId;
  userId: Types.ObjectId;
  answers: ISubmittedAnswer[];
  score: number;       // percentage
  totalQuestions: number;
  correctAnswers: number;
  passed: boolean;
  attemptNumber: number;
  submittedAt: Date;
}

/**
 * Attempt result returned to the convert after submission.
 */
export interface AttemptResultView {
  attemptId: string;
  score: number;
  totalQuestions: number;
  correctAnswers: number;
  passed: boolean;
  passingScore: number;
  attemptNumber: number;
  answers: Array<{
    questionId: string;
    selectedLabel: string;
    correctLabel: string;
    isCorrect: boolean;
  }>;
  submittedAt: Date;
}

/**
 * Summary of a convert's quiz attempts for admin view.
 */
export interface AttemptSummaryView {
  attemptId: string;
  score: number;
  passed: boolean;
  attemptNumber: number;
  submittedAt: Date;
}

const submittedAnswerSchema = new Schema<ISubmittedAnswer>(
  {
    questionId: {
      type: String,
      required: true,
    },
    selectedLabel: {
      type: String,
      required: true,
      trim: true,
    },
    isCorrect: {
      type: Boolean,
      default: false,
    },
  },
  { _id: false }
);

const quizAttemptSchema = new Schema<IQuizAttempt>(
  {
    quizId: {
      type: Schema.Types.ObjectId,
      ref: 'Quiz',
      required: true,
    },
    lessonId: {
      type: Schema.Types.ObjectId,
      ref: 'Lesson',
      required: true,
    },
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    answers: {
      type: [submittedAnswerSchema],
      required: true,
    },
    score: {
      type: Number,
      required: true,
      min: 0,
      max: 100,
    },
    totalQuestions: {
      type: Number,
      required: true,
      min: 1,
    },
    correctAnswers: {
      type: Number,
      required: true,
      min: 0,
    },
    passed: {
      type: Boolean,
      required: true,
    },
    attemptNumber: {
      type: Number,
      required: true,
      min: 1,
    },
    submittedAt: {
      type: Date,
      required: true,
      default: Date.now,
    },
  },
  {
    timestamps: false,
    toJSON: {
      transform(_doc, ret: Record<string, unknown>) {
        delete ret.__v;
        return ret;
      },
    },
  }
);

// User's attempts for a quiz (newest first)
quizAttemptSchema.index({ userId: 1, quizId: 1, submittedAt: -1 });

// Admin: all attempts for a lesson
quizAttemptSchema.index({ lessonId: 1, submittedAt: -1 });

// ──────────────────────────────────────────
// Transform helpers
// ──────────────────────────────────────────

export function toQuizPublicView(quiz: IQuiz): QuizPublicView {
  return {
    id: quiz._id.toString(),
    lessonId: quiz.lessonId.toString(),
    title: quiz.title,
    description: quiz.description,
    questions: quiz.questions
      .sort((a, b) => a.sortOrder - b.sortOrder)
      .map((q) => ({
        id: q._id.toString(),
        questionText: q.questionText,
        options: q.options,
        sortOrder: q.sortOrder,
      })),
    passingScore: quiz.passingScore,
    maxAttempts: quiz.maxAttempts,
    totalQuestions: quiz.questions.length,
  };
}

export function toQuizAdminView(quiz: IQuiz): QuizAdminView {
  return {
    id: quiz._id.toString(),
    lessonId: quiz.lessonId.toString(),
    courseId: quiz.courseId.toString(),
    title: quiz.title,
    description: quiz.description,
    questions: quiz.questions
      .sort((a, b) => a.sortOrder - b.sortOrder)
      .map((q) => ({
        id: q._id.toString(),
        questionText: q.questionText,
        options: q.options,
        correctLabel: q.correctLabel,
        sortOrder: q.sortOrder,
      })),
    passingScore: quiz.passingScore,
    maxAttempts: quiz.maxAttempts,
    totalQuestions: quiz.questions.length,
    isActive: quiz.isActive,
    createdAt: quiz.createdAt,
    updatedAt: quiz.updatedAt,
  };
}

export const Quiz = mongoose.model<IQuiz>('Quiz', quizSchema);
export const QuizAttempt = mongoose.model<IQuizAttempt>('QuizAttempt', quizAttemptSchema);
